### ISSUE TITLE
Kontonummern konfgurierbar machen

### ISSUE THREAD

**Issue by Benny739** [jonaswitt/stripe-datev-exporter#11]
Hi,

mein Vorschlag für die konfigurierbaren Kontonummern (würde ich in config.py hinzufügen):

```
bank_account = "1201"
stripe_fees_account = "70025"
stripe_transit_account = "1360"

sammel_debitor = "10001"
account_prap = "990"

account_rev_germany = "8400"
datev_tax_key_rev_germany = ""

account_rev_eu_reverse = "8336"
datev_tax_key_rev_eu_reverse = "40"

account_rev_moss = ""
datev_tax_key_rev_moss = ""

account_rev_world = "8338"
datev_tax_key_rev_word = "40"
```

Offene Konten (hier weiß ich nicht wofür diese genau sind):
- 4600
- 4909
Hast du hier Vorschläge für naming?

Ich habe für jedes Konto noch einen "datev_tax_key" hinzugefügt, damit man hier flexibler ist. Wir brauchen z.b. nur bei den MOSS Buchungen den zusätzlichen Buchungsschlüssel.

PR kommt wenn du dein ok gibst.

**Comment by jonaswitt** [comment]
Wir nutzen SKR03 und die Kontennummern kommen daher. 

4600 = Werbungskosten
4909 = Fremdleistungen
8336 = Erlöse aus im anderen EU-Land steuerpflichtigen sonstigen Leis- tungen, für die der Leistungsemp- fänger die Umsatzsteuer schuldet
8338 = Erlöse aus im Drittland steuerbaren Leistungen, im Inland nicht steuer- bare Umsätze
8400 = Erlöse 19% USt

Vom Ansatz her grundsätzlich okay für mich. 

Ich habe in den nächsten 2,5 Wochen nicht viel Zeit, aber erstelle gerne PRs und arbeite weiter damit wie du's brauchst. Es kann nur sein, dass es eine Weile dauert bis von mir eine Antwort kommt. Vielen Dank für dein Engagement jedenfalls!
