### ISSUE TITLE
error on download for my test account

### ISSUE THREAD

**Issue by Henner** [jonaswitt/stripe-datev-exporter#16]
Hi,

I do get an error using the latest from master branch:

python3 stripe-datev-cli.py download 2024 1
Retrieving data between 2024-01-01 and 2024-01-31 (inclusive, Europe/Berlin)
Retrieved 0 invoice(s), total 0 EUR
Retrieved 4 balance transaction(s), 3 charge(s), total 68 EUR
Traceback (most recent call last):
  File "stripe-datev-cli.py", line 268, in <module>
    StripeDatevCli().run(sys.argv)
  File "stripe-datev-cli.py", line 52, in run
    getattr(self, args.command)(argv[2:])
  File "stripe-datev-cli.py", line 92, in download
    revenue_items += stripe_datev.charges.createRevenueItems(direct_charges)
  File "/home/vagrant/stripe-datev-exporter/stripe_datev/charges.py", line 59, in createRevenueItems
    if "in_" in charge.description:
TypeError: argument of type 'NoneType' is not iterable

**Comment by jonaswitt** [comment]
Try the fix I pushed to my branch `jonaswitt-patch-1`

**Comment by Henner** [comment]
error still exists

**Comment by jonaswitt** [comment]
Could you post the full output when running on the patch branch?

**Comment by Henner** [comment]
git status
On branch jonaswitt-patch-1
nothing to commit, working tree clean

python3 stripe-datev-cli.py download 2024 1
Retrieving data between 2024-01-01 and 2024-01-31 (inclusive, Europe/Berlin)
Retrieved 0 invoice(s), total 0 EUR
Retrieved 4 balance transaction(s), 3 charge(s), total 68 EUR
Traceback (most recent call last):
  File "stripe-datev-cli.py", line 268, in <module>
    StripeDatevCli().run(sys.argv)
  File "stripe-datev-cli.py", line 52, in run
    getattr(self, args.command)(argv[2:])
  File "stripe-datev-cli.py", line 92, in download
    revenue_items += stripe_datev.charges.createRevenueItems(direct_charges)
  File "/home/vagrant/stripe-datev-exporter/stripe_datev/charges.py", line 59, in createRevenueItems
    if "in_" in charge.description:
TypeError: argument of type 'NoneType' is not iterable

**Comment by jonaswitt** [comment]
I don't know what you vagrant setup is, perhaps you didn't copy the latest file? `stripe_datev/charges.py` line 59 looks different than what's in your error message: https://github.com/jonaswitt/stripe-datev-exporter/blob/jonaswitt-patch-1/stripe_datev/charges.py#L59
