### ISSUE TITLE
Feature Ideas & Questions

### ISSUE THREAD

**Issue by Benny739** [jonaswitt/stripe-datev-exporter#7]
I've made a few observations, I would appreciate if you can give me your opinion on some things:

1. I think we should also consider "pre_payment_credit_notes_amount" when checking for creditnotes
2. The credit notes should also be exported imho
3. The timestamps for retrieving invoices should be UTC, otherwise invoices could be missing or exported in the wrong month 
4. How do you deal with creditnotes wich are generated in the next month?
5. Are you using Belegtransfer or uploading the pdfs in another form to datev? 

I could create a PR for 1 & 2

Edit:
6. Do you prefer configurable account numbers in the env file or in the config file?

**Comment by jonaswitt** [comment]
> 1. I think we should also consider "pre_payment_credit_notes_amount" when checking for creditnotes

Probably, I haven't had such an invoice yet. In general, this repository will not necessarily deal with all possible cases in the entire Stripe API, only those that we have encountered.

> 2. The credit notes should also be exported imho

What do you propose exactly? We deal with credit notes, see 4. below

> 3. The timestamps for retrieving invoices should be UTC, otherwise invoices could be missing or exported in the wrong month

Timestamps for retrieving invoices are in local timezone intentionally. I'm not an accountant but accounting is done in local time, I believe. I don't think invoices will be missing because of that. 

> 4. How do you deal with creditnotes wich are generated in the next month?

See

https://github.com/jonaswitt/stripe-datev-exporter/blob/9399d8ef920d5e6da18228c64152df83f8ec65d1/stripe_datev/invoices.py#L259C10-L259C21

and other references to `credited_at`

> 5. Are you using Belegtransfer or uploading the pdfs in another form to datev?

No

> Edit: 6. Do you prefer configurable account numbers in the env file or in the config file?

Config file. Env file is for secrets.

**Comment by Benny739** [comment]
Ich Wechsel mal auf Deutsch, falls du lieber in Englisch bleiben willst einfach kurz sagen.

Ich kann gut verstehen wenn du das Repository lieber als Template belassen möchtest, dann würde ich einfach in meinem Fork weiter arbeiten. 
Ich würde keine großen Anpassungen vornehmen, aber uU kann das Tool und Prozesse verbessert werden, wenn mehrere Leute daran arbeiten :) Perse ist das Tool schon sehr gut und ich denke, dass man es ohne große Anpassungen generell nutzbarer machen könnte. 

Wäre es in Ordnung wenn wir auf "autopep8" oder den "black" formatter setzen? 
Aktuell werden beim auto formatieren quasi alle Dateien geändert.
Default Tab Size ist (zumindest in vscode) 4, wenn du die gerne bei 2 lassen möchtest sollten wir das in der settings.json festhalten (am besten zusammen mit einem defaultFormatter)

Falls die Formatierungsänderungen für dich in Ordnung sind würde ich 1 PR erstellen, der erstmal nur die Formatierungen aktualisiert. Das wäre auch sehr hilfreich, wenn du das repository als template belassen möchtest, so wird es einfacher upstream zu mergen.

> What do you propose exactly? We deal with credit notes, see 4. below

Generell würde ich einfach nur die Gutschriften zu den Rechnungen auch als pdf exportieren.
Wir nutzen bei uns den Datev Belegtransfer. Hierzu muss man eine zip mit allen Rechnungen und einer document.xml erstellen. In der XML bekommt jede Rechnung eine guid, in der CSV verweist man dann Feld "Beleglink" auf die Guid.
Diese ZIP kann man bei Datev hochladen und dann ist jeder Buchungssatz automatisch mit der korrekten pdf verlinkt.

Dieses Modul würde ich gerne bauen und in der config ein setting machen, ob der Belegtransfer genutzt werden soll oder nicht.
 
> Timestamps for retrieving invoices are in local timezone intentionally. I'm not an accountant but accounting is done in local time, I believe. I don't think invoices will be missing because of that.

In meinen tests hat eine Rechnung vom 30.09 22:30 Uhr (unser Zeit) gefehlt, daher bin ich drauf gekommen. Mit UTC Zeitzone war die Rechnung enthalten. ich glaube stripe speichert die timestamps als UTC.
Ich werde das aber nochmal genau prüfen.

**Comment by jonaswitt** [comment]
> Wäre es in Ordnung wenn wir auf "autopep8" oder den "black" formatter setzen? Aktuell werden beim auto formatieren quasi alle Dateien geändert. Default Tab Size ist (zumindest in vscode) 4, wenn du die gerne bei 2 lassen möchtest sollten wir das in der settings.json festhalten (am besten zusammen mit einem defaultFormatter)
> 
> Falls die Formatierungsänderungen für dich in Ordnung sind würde ich 1 PR erstellen, der erstmal nur die Formatierungen aktualisiert. Das wäre auch sehr hilfreich, wenn du das repository als template belassen möchtest, so wird es einfacher upstream zu mergen.

Ok, gerne. Meine Präferenz wäre weiter 2 spaces als indent zu nutzen.

> Generell würde ich die Gutschriften zu den Rechnungen auch exportieren

Du meinst die PDFs? Das habe ich zuerst nicht verstanden. In dem Fall, ja, gerne.

> Wir nutzen bei uns den Datev Belegtransfer. Hierzu muss man eine zip mit allen Rechnungen und einer document.xml erstellen. In der XML bekommt jede Rechnung eine guid, in der CSV verweist man dann Feld "Beleglink" auf die Guid. Diese ZIP kann man bei Datev hochladen und dann ist jeder Buchungssatz automatisch mit der korrekten pdf verlinkt.
> 
> Dieses Modul würde ich gerne bauen und in der config ein setting machen, ob der Belegtransfer genutzt werden soll oder nicht.

Gerne. Das benötigt aus meiner Sicht auch gar kein setting, es schadet ja niemandem wenn's an ist.

> ich glaube stripe speichert die timestamps als UTC.

Soweit auch mein Kenntnisstand, ja. Daher nutzen wir immer `datetime.fromtimestamp(invoice.created, timezone.utc).astimezone(config.accounting_tz)`

Danke für deine Unterstützung!
