### ISSUE TITLE
Handling Gutschriften verändern

### ISSUE THREAD

**Issue by Benny739** [jonaswitt/stripe-datev-exporter#9]
Hi,

ich denke es würde Sinn machen das Handling der Gutschriften zu überarbeiten, da es Fälle gibt, in denen die Gutschriften nicht verbucht werden. 
Bsp:
- Kunde kauft am 15 Februar einen Jahrestarif
- Buchhaltung für Februar wird im März abgeschlossen
- Kunde ruft Lastschrift 8 Wochen später zurück = 15 April
- Gutschrift wird nach 8 Wochen erstellt = 15 April

In diesem Fall wird die Gutschrift nicht exportiert, da sie außerhalb des Monats Februar liegt.
Aktuell müsste man die Datei "EXTF_2023-4_Revenue_From_2023-02.csv" nochmal neu generieren lassen, damit im April dann korrekt die Ausbuchung statt findet. 
Um hier sicher zu gehen, dass keine Fehler passieren, müsste man jeden Monat die letzten X Monate nochmal neu generieren, damit man aktuelle forward_month import Dateien hat. Man kann ja nicht ausschließen, dass nach 4 oder 6 Monate noch eine Gutschrift erstellt wurde.

Mein Vorschlag:
- Wir laden alle Gutschriften die im Buchhaltungsmonat erstellt wurden
- Laden alle dazugehörigen Rechnungen
- Lassen dann die Ausbuchung durch die "invoices.createAccountingRecords" erstellen
- Man müsste die Funktion nur um 1 Parameter erweitern, dass sie in diesen Fällen dann nicht die Daten für Februar nochmal erstellt, sondern nur die Ausbuchungen in April

Ich habe das ganze bereits getestet und dieser Ansatz würde mir wenig Aufwand das problem beheben.

**Comment by jonaswitt** [comment]
Mach doch gerne mal einen konkreten Vorschlag mit Code. Wir sind mit "die letzten X Monate nochmal neu generieren" bisher ganz okay klargekommen, aber es erfordert einen gewissen Überblick über die Geschäftsvorgänge und könnte verbessert werden, da hast du Recht.

Der Ansatz mit "lade alle Gutschriften die im Buchhaltungsmonat erstellt wurden" ist nicht verkehrt, aber m.M.n. musst du dann nicht nur die dazugehörigen Rechnungen laden, sondern _alle_ Rechnungen aus den betroffenen Vormonaten. Sonst kannst du die Datei "EXTF_2023-4_Revenue_From_2023-02.csv" bspw. nicht garantiert vollständig neu generieren.

**Comment by Benny739** [comment]
Gibt es bei euch den Fall, dass es in einer Rechnung unterschiedliche Laufzeiten für Rechnungsposten gibt?
Ansonsten könnte man die Laufzeit für eine ganze Rechnung ermitteln und den Gesamtbetrag aufteilen.

Das Handling von Gutschriften wird dann einfacher, da man einfach den Betrag der Gutschrift auf die Rechnungslaufzeit umlegen kann und jede Gutschrift separat verbuchen kann.
Dann wäre es auch möglich 2 Gutschriften in unterschiedlichen Monaten für 1 Rechnung zu verbuchen.

In der Sofware die wir davor genutzt haben, wurden die Gutschriften genau wie die Rechnungen month over month ausgebucht und der prap der Rechnung gar nicht angepasst bei einer Gutschrift. Ist effektiv dann jeden Monat ein 0 Summen Spiel.

**Comment by jonaswitt** [comment]
> Gibt es bei euch den Fall, dass es in einer Rechnung unterschiedliche Laufzeiten für Rechnungsposten gibt? 

Ja. Die Stripe API sieht das ja auch vor, da `period` auf dem line item definiert ist.

**Comment by Benny739** [comment]
Erinnerst du dich, warum du die discounts für jedes item manuell berechnet hast?
Aktuell wird leider der pRAP falsch berechnet, wenn sich Coupons auf Rechnungsebene nur auf 1 Produkt beziehen.
Man muss hierfür in den discount_amounts prüfen ob der Coupon auf Rechnungsebene auch tatsächlich angewendet wurde.

Allerdings kann man das ganze erheblich vereinfachen.

Bei den invoices kommt von stripe für jedes item die discounts mit
```
"discount_amounts": [
          {
            "amount": 40000,
            "discount": "di_1O5zMjDc6Ds2E1iC9SCSHtgM"
          },
          {
            "amount": 16000,
            "discount": "di_1O5zOdDc6Ds2E1iC808nFibF"
          }
        ],
```

Um den Fehler zu beben, müsste man als discount für die items lediglich die discount_amounts pro item aufsummieren. 
Das kalkulieren mit den coupons kann man komplett weg lassen. Die amounts beinhalten alle discounts, egal ob Rechnungsebene oder itemebene.

Was mir noch aufgefallen ist, es gibt pro line item die property "tax_amounts".
Dieser Array hat  immer nur 1 Element und beinhaltet sowohl den korrekten Netto betrag (abzüglich aller discounts der position und die steuer.
Ein Beispiel:

```
"lines": {
    "object": "list",
    "data": [
      {
        ...
        "amount": 200000,
        "amount_excluding_tax": 200000,
        ...
        "discount_amounts": [
          {
            "amount": 40000,
            "discount": "di_1O5zMjDc6Ds2E1iC9SCSHtgM"
          },
          {
            "amount": 16000,
            "discount": "di_1O5zOdDc6Ds2E1iC808nFibF"
          }
        ],
        ...
        "tax_amounts": [
          {
            "amount": 27360,
            "inclusive": false,
            "tax_rate": "txr_1GWllXDc6Ds2E1iCBY2dIDXE",
            "taxability_reason": null,
            "taxable_amount": 144000
          }
        ],
....
```

Ich sehe nur 2 Fälle:
1. tax_amounts da = mit diesen Beträgen arbeiten
2. keine tax_amounts = den item amount nehmen und discount_amounts abziehen

Das wird das ganze vereinfachen und auch die Fehler beheben.

**Comment by jonaswitt** [comment]
Ich habe zu dem Problem "die letzten Monate neu generieren" in f7963ba Warnhinweise eingebaut. Wenn du das weiter automatisieren willst, mach gerne einen PR.

Zum Thema discounts/line items, ich habe die Sachverhalte nicht, dass ein Discount nur auf einige der Line Items angewendet wird, aber die vorgeschlagene Änderung klingt grundsätzlich sinnvoll, mach auch hier gerne einen PR.
